version: '3'

services:
  microservice:
    build: .docker
    image: lumen-microservice
    depends_on:
      - mysql
      - mysql-test
    volumes:
      - ./src/:/application:cached

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=lumen-microservice
    volumes:
      - db-data:/var/lib/mysql:cached

  mysql-test:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=testing

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro,cached
    depends_on:
      - microservice

volumes:
  db-data:
